#!/bin/bash

echo "🔍 Checking Docker Compose configuration..."
docker-compose config

echo ""
echo "📋 Docker Compose Configuration Summary:"
echo "========================================"
echo "✅ Backend Service:"
echo "   - Ports: 5000:80, 5001:443"
echo "   - Environment: Development"
echo "   - Dependencies: PostgreSQL (with health check)"
echo "   - Volumes: Source code mounted for development"
echo ""
echo "✅ PostgreSQL Service:"
echo "   - Port: 5432:5432"
echo "   - Database: cvapp"
echo "   - User: postgres"
echo "   - Health Check: Enabled"
echo ""
echo "✅ Networks:"
echo "   - app-network (bridge)"
echo ""
echo "✅ Volumes:"
echo "   - postgres_data (persistent)"
echo ""
echo "🚀 To start the application:"
echo "   docker-compose up --build"
echo ""
echo "🌐 Access points:"
echo "   - Web App: http://localhost:5000"
echo "   - Database: localhost:5432"
