FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

# Install EF Core tools
RUN dotnet tool install --global dotnet-ef

# Add tools to PATH
ENV PATH="/root/.dotnet/tools:${PATH}"

EXPOSE 80

# The source code will be mounted as a volume for hot reload
CMD ["dotnet", "watch", "run", "--urls", "http://+:80", "--no-launch-profile"]
