import express, { Application, Request, Response } from 'express';
import { createExpressServer } from 'routing-controllers';
import dotenv from 'dotenv';
import path from 'path';

import fs from 'fs/promises';
import pug from 'pug';
import fetch from 'node-fetch';
import FormData from 'form-data';

dotenv.config();

/**
 * Server class
 * @class
 */
export class Server {
  /** @type {express.Application} */
  private app: express.Application;
  /** @type {number} */
  private port: number;
  private readonly publicTemplatesDir: string;
  private readonly viewsDir: string;

  /**
   * Server constructor
   * initializes express server
   * and sets listening port
   * @constructor
   * @returns void
   */
  public constructor() {
    this.app = createExpressServer({
      cors: true,
      defaultErrorHandler: false,
      controllers: [path.join(__dirname + '/../controllers/*.js')],
    });

    this.port = Number(process.env.PORT) || 3000;

    this.publicTemplatesDir = path.join(__dirname, '..', 'public', 'templates');
    this.viewsDir = path.join(__dirname, '..', 'views');

    this.configureMiddleware();
    this.configureRoutes();
  }

  private configureMiddleware(): void {
    this.app.use(express.json());

    // Serve generated HTML files as static assets
    this.app.use('/templates', express.static(this.publicTemplatesDir));
  }

  private configureRoutes(): void {
    this.app.post(
      '/generate/template/:templateSlug',
      this.generateFromTemplate,
    );
    this.app.get('/generate/template/:templateSlug', this.generateFromTemplate);
    this.app.get('/templates/:templateSlug', this.serveHTML);
  }

  /**
   * Listen method
   * @memberof Server
   * @returns void
   */
  public listen(): void {
    this.app.listen(this.port, () => {
      console.log(`Server running on port ${this.port}`);
    });
  }
  /**
   * generateFromTemplate
   *
   * - Renders a Pug template identified by :templateSlug with JSON POST body
   * - Saves HTML under public/templates/[templateSlug].html
   * - Calls Gotenberg to convert that URL into a PDF and returns the PDF
   */
  private generateFromTemplate = async (req: Request, res: Response) => {
    console.log('TEST', req.params.templateSlug);
    const templateSlug = req.params.templateSlug;

    const ENV_APP_URL =
      process.env.ENV_APP_URL || `http://localhost:${this.port}`;
    const ENV_GOTENBERG_URL = process.env.ENV_GOTENBERG_URL;

    if (!ENV_GOTENBERG_URL) {
      return res
        .status(500)
        .json({ error: 'ENV_GOTENBERG_URL must be defined' });
    }

    try {
      // 1. Render the Pug template with the JSON body as locals
      const pugPath = path.join(this.viewsDir, `${templateSlug}.pug`);
      const htmlFromPug = pug.renderFile(pugPath, req.body || {});

      // 2. Save HTML to public/templates/[templateSlug].html
      const htmlFilePath = path.join(
        this.publicTemplatesDir,
        `${templateSlug}.html`,
      );

      await fs.mkdir(path.dirname(htmlFilePath), { recursive: true });
      await fs.writeFile(htmlFilePath, htmlFromPug, 'utf8');

      // 3. Build URL to the generated HTML
      const htmlUrl = `${ENV_APP_URL}/templates/${templateSlug}`;

      // 4. Call Gotenberg (curl equivalent)
      const gotenbergEndpoint = `${ENV_GOTENBERG_URL}/forms/chromium/convert/url`;
      const form = new FormData();
      form.append('url', htmlUrl);

      console.log('gotenbergEndpoint', gotenbergEndpoint);
      console.log('htmlUrl', htmlUrl);

      const gotenbergResponse = await fetch(gotenbergEndpoint, {
        method: 'POST',
        body: form as any,
        headers: (form as any).getHeaders
          ? (form as any).getHeaders()
          : undefined,
      });

      if (!gotenbergResponse.ok) {
        const text = await gotenbergResponse.text().catch(() => '');
        return res.status(502).json({
          error: 'Gotenberg conversion failed',
          status: gotenbergResponse.status,
          body: text,
        });
      }

      const arrayBuffer = await gotenbergResponse.arrayBuffer();
      const pdfBuffer = Buffer.from(arrayBuffer);

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader(
        'Content-Disposition',
        `attachment; filename="${templateSlug}.pdf"`,
      );
      return res.send(pdfBuffer);
    } catch (err: any) {
      console.error('generateFromTemplate error:', err);
      return res.status(500).json({
        error: 'Failed to generate template',
        details: err?.message ?? String(err),
      });
    }
  };

  /**
   * serveHTML
   * GET {ENV_APP_URL}/templates/:templateSlug.html
   *
   * Serves the HTML generated by generateFromTemplate()
   */
  private serveHTML = async (req: Request, res: Response) => {
    const templateSlug = req.params.templateSlug;
    const htmlFilePath = path.join(
      this.publicTemplatesDir,
      `${templateSlug}.html`,
    );

    try {
      await fs.access(htmlFilePath);
      return res.sendFile(htmlFilePath);
    } catch {
      return res.status(404).send('Generated template not found');
    }
  };
}
